# Generated by Django 5.2b1 on 2025-03-01 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0001_initial_squashed_0004_alter_item_description"),
        ("catalog", "0005_alter_item_description_alter_item_price"),
        ("catalog", "0006_alter_item_price"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимум 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="имя",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Максимум 512 символов",
                        max_length=512,
                        verbose_name="описание",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Стоимость в долларах (2 знака после точки)",
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name="стоимость",
                    ),
                ),
                (
                    "payment_price_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="идентификатор платёжной системы",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
