# Generated by Django 5.2b1 on 2025-03-01 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0001_initial"),
        ("catalog", "0002_alter_item_options_item_payment_price_id"),
        ("catalog", "0003_alter_item_price"),
        ("catalog", "0004_alter_item_description"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимум 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="имя",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=512, verbose_name="описание"),
                ),
                (
                    "price",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name="стоимость",
                    ),
                ),
                (
                    "payment_price_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="идентификатор платёжной системы",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
